### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by thestalker12** [zedafty/stalker#8]
Hi friend, Im looking into the RPG that this sheet is for. Could you by chance link it or a place to get it?
only way I can contact you as far ive found

**Comment by zedafty** [comment]
Hello Stalker12 !
Sure, you can see the rules on at this adress [Calameo](https://fr.calameo.com/read/00094477423131a37ec74).
They are written in french, hope this won't be a matter for you :)

**Comment by thestalker12** [comment]
Thanks Brother wish you well
